AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false


Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleCopDisableDirective:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
