name: build

on: [pull_request]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2']
    name: 💎 Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0 # gives the commit linter access to previous commits

      - name: Commit message linter
        if: ${{ matrix.ruby == '2.5' }}
        uses: wagoid/commitlint-github-action@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - env:
          STREAM_API_KEY: ${{ secrets.STREAM_API_KEY }}
          STREAM_API_SECRET: ${{ secrets.STREAM_API_SECRET }}
        run: |
          bundle exec rake rubocop
          bundle exec rake test
